import { Contact } from "@/types/contact";

export const demoContacts: Contact[] = [
  {
    FirstName: "Alice",
    LastName: "Johnson",
    Company: "Tech Innovations",
    Address: {
      Line1: "123 Maple St",
      Line2: "Apt 4B",
      Line3: "Springfield",
      PostCode: "12345",
    },
    Email: "alice.johnson@techinnovations.com",
    PhoneNo: "555-1234",
    ServiceStart: "2024-01-15",
    ServiceFreq: 30,
    NextService: "2024-02-14",
    ContactId: "C001",
  },
  {
    FirstName: "Bob",
    LastName: "Smith",
    Company: "Creative Solutions",
    Address: {
      Line1: "456 Oak St",
      Line2: "",
      Line3: "Springfield",
      PostCode: "12346",
    },
    Email: "bob.smith@creativesolutions.com",
    PhoneNo: "555-5678",
    ServiceStart: "2024-02-01",
    ServiceFreq: 14,
    NextService: "2024-02-15",
    ContactId: "C002",
  },
  {
    FirstName: "Carol",
    LastName: "Davis",
    Company: "Global Enterprises",
    Address: {
      Line1: "789 Pine St",
      Line2: "Suite 100",
      Line3: "Springfield",
      PostCode: "12347",
    },
    Email: "carol.davis@globalenterprises.com",
    PhoneNo: "555-8765",
    ServiceStart: "2024-01-20",
    ServiceFreq: 60,
    NextService: "2024-03-20",
    ContactId: "C003",
  },
  {
    FirstName: "David",
    LastName: "Brown",
    Company: "Marketing Pros",
    Address: {
      Line1: "321 Elm St",
      Line2: "",
      Line3: "Springfield",
      PostCode: "12348",
    },
    Email: "david.brown@marketingpros.com",
    PhoneNo: "555-4321",
    ServiceStart: "2024-03-05",
    ServiceFreq: 7,
    NextService: "2024-03-12",
    ContactId: "C004",
  },
  {
    FirstName: "Eve",
    LastName: "Clark",
    Company: "Design Studio",
    Address: {
      Line1: "654 Birch St",
      Line2: "Floor 3",
      Line3: "Springfield",
      PostCode: "12349",
    },
    Email: "eve.clark@designstudio.com",
    PhoneNo: "555-9876",
    ServiceStart: "2024-02-10",
    ServiceFreq: 30,
    NextService: "2024-03-11",
    ContactId: "C005",
  },
  {
    FirstName: "Frank",
    LastName: "Wilson",
    Company: "Consulting Group",
    Address: {
      Line1: "987 Cedar St",
      Line2: "",
      Line3: "Springfield",
      PostCode: "12350",
    },
    Email: "frank.wilson@consultinggroup.com",
    PhoneNo: "555-6543",
    ServiceStart: "2024-04-01",
    ServiceFreq: 90,
    NextService: "2024-07-01",
    ContactId: "C006",
  },
  {
    FirstName: "Grace",
    LastName: "Moore",
    Company: "Finance Corp",
    Address: {
      Line1: "258 Fir St",
      Line2: "",
      Line3: "Springfield",
      PostCode: "12351",
    },
    Email: "grace.moore@financecorp.com",
    PhoneNo: "555-3210",
    ServiceStart: "2024-01-30",
    ServiceFreq: 60,
    NextService: "2024-03-30",
    ContactId: "C007",
  },
  {
    FirstName: "Henry",
    LastName: "Taylor",
    Company: "Logistics LLC",
    Address: {
      Line1: "369 Spruce St",
      Line2: "Unit 5",
      Line3: "Springfield",
      PostCode: "12352",
    },
    Email: "henry.taylor@logisticsllc.com",
    PhoneNo: "555-0987",
    ServiceStart: "2024-02-15",
    ServiceFreq: 30,
    NextService: "2024-03-15",
    ContactId: "C008",
  },
  {
    FirstName: "Ivy",
    LastName: "Anderson",
    Company: "Health Services",
    Address: {
      Line1: "147 Willow St",
      Line2: "Suite 200",
      Line3: "Springfield",
      PostCode: "12353",
    },
    Email: "ivy.anderson@healthservices.com",
    PhoneNo: "555-1357",
    ServiceStart: "2024-01-25",
    ServiceFreq: 30,
    NextService: "2024-02-24",
    ContactId: "C009",
  },
  {
    FirstName: "Jack",
    LastName: "Thomas",
    Company: "Retail Solutions",
    Address: {
      Line1: "753 Cherry St",
      Line2: "",
      Line3: "Springfield",
      PostCode: "12354",
    },
    Email: "jack.thomas@retailsolutions.com",
    PhoneNo: "555-2468",
    ServiceStart: "2024-03-20",
    ServiceFreq: 14,
    NextService: "2024-04-03",
    ContactId: "C010",
  },
];
