name: Build and deploy website
on:
  push:
    branches:
      - main
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: "eu-west-2"
jobs:
  build-deploy:
    environment: prod
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

###########################################################################
############### Client
###########################################################################
      - name: install
        id: install
        working-directory: ./client
        run: make npm/install
        continue-on-error: false

      # - name: lint
      #   id: lint
      #   run: make lint/application
      #   continue-on-error: false

      # - name: test
      #   id: test
      #   run: make test/application
      #   continue-on-error: false

      - name: build
        id: build
        working-directory: ./client
        run: make build/application
        continue-on-error: false

      - name: rewrite
        id: rewrite
        working-directory: ./client
        run: make rewrite/extension
        continue-on-error: false

      - name: clear s3
        id: clear
        working-directory: ./client
        run: make s3/clean
        continue-on-error: false

      - name: sync html files
        id: synchtml
        working-directory: ./client
        run: make s3/push/html
        continue-on-error: false

      - name: sync remaining files
        id: syncremaining
        working-directory: ./client
        run: make s3/push/remaining
        continue-on-error: false

      - name: refresh cloudfront
        id: cloudfront
        working-directory: ./client
        run: make cloudfront/cache/refresh
        continue-on-error: false

###########################################################################
############### Server
###########################################################################

      - name: Build server binary
        id: binary
        working-directory: ./server
        run: make server/build
        continue-on-error: false

      - name: Zip server binary
        id: zip-binary
        working-directory: ./server
        run: make server/zip
        continue-on-error: false

      - name: Update lambda function
        id: update-lambda
        working-directory: ./server
        run: aws/lambda/update/actions
        continue-on-error: false